includes=(
    ~/.zsh/aliases
    ~/.zsh/asdf
    ~/.zsh/autocorrect
    ~/.zsh/completions
    ~/.zsh/exports
    ~/.zsh/history
    ~/.zsh/homebrew
    ~/.zsh/hooks
    ~/.zsh/oh-my-zsh
    ~/.zsh/paths
    ~/.zsh/plugins
    ~/.fzf.zsh
    ~/.zsh/zshrc-`hostname -s`
)

for config in $includes; do
    if [[ -f $config ]]; then
        source $config
    fi
done

