includes=(
    ~/.zsh/aliases
    ~/.zsh/exports
    ~/.zsh/history
    ~/.zsh/hooks
    ~/.zsh/oh-my-zsh
    ~/.zsh/paths
    ~/.zsh/plugins
    ~/.zsh/autocorrect
    ~/.fzf.zsh
    # ~/google-cloud-sdk/completion.zsh.inc
    # ~/google-cloud-sdk/path.zsh.inc
    /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
    # ~/.zsh/zshrc-`hostname -s`
)

for config in $includes; do
    if [[ -f $config ]]; then
        source $config
    fi
done

export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters

# export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

# # The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/efritz/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/efritz/google-cloud-sdk/path.zsh.inc'; fi

# # The next line enables shell command completion for gcloud.
# if [ -f '/Users/efritz/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/efritz/google-cloud-sdk/completion.zsh.inc'; fi

autoload -U +X bashcompinit && bashcompinit
# complete -o nospace -C /usr/local/bin/mc mc

# # For sqlite3
# export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/efritz/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/efritz/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/efritz/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/efritz/google-cloud-sdk/completion.zsh.inc'; fi
