#!/bin/bash

# Allow aliases to be used with sudo
alias sudo="sudo "

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"
alias -- -="cd -"

# Frequent commands
alias o='open -a Finder .'
alias s='open -a "Sublime Text" .'
alias c='open -a "Google Chrome"'
alias b='open -a "Google Chrome"'

# Sane default flags
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
alias ls='ls -GFh'
alias grep='grep --color=auto'

# Filesize
alias fs="stat -f \"%z bytes\""

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"

# Remove DS_Store files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Extract archives
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)           echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
