#!/usr/bin/env bash

# Custom aliases
alias real='cd `pwd -P`'
alias code=code-insiders

# Pass aliases over through sudo
alias sudo='sudo '

# Safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias ln='ln -i'

# Color support
alias grep='grep --color=auto'

# macOS uses BSD ls which does not support the long flags
# Instead, install gls with `brew install coreutils`
alias ls='gls -hF --group-directories-first --color=auto'

# Actual aliases
alias real='cd `pwd -P`'
