#!/usr/bin/env bash

#
# Define common colors (see http://git.io/solarized-colors)

tput sgr0;
bold=$(tput bold);
reset=$(tput sgr0);
black=$(tput setaf 0);
blue=$(tput setaf 33);
cyan=$(tput setaf 37);
green=$(tput setaf 64);
orange=$(tput setaf 166);
purple=$(tput setaf 125);
red=$(tput setaf 124);
violet=$(tput setaf 61);
white=$(tput setaf 15);
yellow=$(tput setaf 136);

user_style() {
    # Highlight the user name when logged in as root.
    if [[ "${USER}" == "root" ]]; then echo "${bold}${red}"; else echo "${blue}"; fi;
}

host_style() {
    # Highlight the host name when connected via SSH.
    if [[ "${SSH_TTY}" ]]; then echo "${bold}${red}"; else echo "${cyan}"; fi;
}

prompt_git_branch() {
    local s="$(current_git_branch)"

    if [ -n "${s}" ]; then
        echo " on ${s}";
    fi;
}

prompt_git_status() {
    local s="$(current_git_status)"

    if [ -n "${s}" ]; then
        echo " [${s}]";
    fi;
}

PS1=""
PS1+="\[$(user_style)\]\u"
PS1+="\[${reset}\]@"
PS1+="\[$(host_style)\]\h"
PS1+="\[${reset}\]:"
PS1+="\w/"
PS1+="\[${violet}\]\$(prompt_git_branch)\[${red}\]\$(prompt_git_status)"
PS1+="\[${white}\] \$ "
PS1+="\[${reset}\]"
export PS1;

PS2="\[${yellow}\]> \[${reset}\]";
export PS2;
